kind: pipeline
name: default

steps:
# Update changelog and API documentation, then push it to sdk repository.
- name: test-changelog
  image: quay.io/openware/sdk-tools:chglog1
  environment:
    BOT_USERNAME: kite-bot
    BOT_NAME: Kite Bot
    BOT_EMAIL: kite-bot@heliostech.fr
    REPO_NAME: ${DRONE_REPO}
    BRANCH_NAME: ${DRONE_BRANCH}
    SDK_BRANCH: test
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - cd /sdk
    - bundle exec rake ci:pull ci:copy_docs[/drone/src] ci:push
  when:
    event:
      - push

- name: telegram-and-slack-notifying
  image: quay.io/openware/sdk-tools:chglog2
  environment:
    REPO_NAME: ${DRONE_REPO}
    BRANCH_NAME: master
    TELEGRAM_BOT_TOKEN:
      from_secret: telegram_bot_token
    TELEGRAM_CHAT_ID:
      from_secret: telegram_chat_id
    GITHUB_API_KEY:
      from_secret: kite_bot_key
  commands:
    - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile sdk:notify:telegram sdk:notify:slack
  when:
    event:
      - push

image_pull_secrets:
  - dockerconfigjson
